name: Release to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write   # Required to push to gh-pages
  pages: write      # Required to deploy to GitHub Pages
  id-token: write   # Required for OIDC authentication

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  Github-Pages-Release:
    timeout-minutes: 10

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - uses: actions/checkout@v4

      # Install stable Rust with Clippy and Rustfmt
      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Add WASM target
        run: rustup target add wasm32-unknown-unknown

      - name: Run Linting
        run: cargo clippy && cargo fmt

      # Install Trunk
      - name: Install Trunk
        run: |
          wget -qO- https://github.com/trunk-rs/trunk/releases/download/v0.18.4/trunk-x86_64-unknown-linux-gnu.tar.gz \
          | tar -xzf-

      # Build with Trunk using public URL (important for GitHub Pages)
      - name: Build Project
        run: ./trunk build --release --public-url "${GITHUB_REPOSITORY#*/}"

      # Optional dummy artifact upload to fix missing download info error
      - name: Upload dummy artifact to load action
        uses: actions/upload-artifact@v3
        with:
          name: dummy
          path: README.md
          retention-days: 1

      # Setup GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v4
        with:
          enablement: true

      # Upload the generated site (dist folder)
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './dist'

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages 🚀
        id: deployment
        uses: actions/deploy-pages@v3
