name: Release to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  Github-Pages-Release:
    timeout-minutes: 10

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Add WASM target
        run: rustup target add wasm32-unknown-unknown

      - name: Run Linting
        run: cargo clippy && cargo fmt

      - name: Install Trunk
        run: |
          wget -qO- https://github.com/trunk-rs/trunk/releases/download/v0.18.4/trunk-x86_64-unknown-linux-gnu.tar.gz \
          | tar -xzf-

      - name: Build Project
        run: ./trunk build --release --public-url "${GITHUB_REPOSITORY#*/}"

      # 👇 Forces GitHub to fetch the upload-artifact action
      - name: Force fetch of upload-artifact
        uses: actions/upload-artifact@v2
        with:
          name: dummy
          path: README.md
          retention-days: 1

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4
        with:
          enablement: true

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './dist'

      - name: Deploy to GitHub Pages 🚀
        id: deployment
        uses: actions/deploy-pages@v3
